.env.example
internal/core/plugin_manager/launcher.go
internal/core/plugin_manager/local_runtime/run.go
internal/core/plugin_manager/local_runtime/type.go
internal/core/plugin_manager/manager.go
internal/types/app/config.go

like the sandbox's proxy config

add proxy config for runtime

---

internal/service/endpoint.go
internal/service/install_service/state.go

currently, disable endpoint not work.

fix disable endpoint not work

---

internal/cluster/clutser_test.go
internal/core/persistence/persistence_test.go
internal/core/plugin_manager/debugging_runtime/connection_key_test.go
internal/core/plugin_manager/debugging_runtime/server_test.go
internal/core/plugin_manager/manager.go
internal/types/app/config.go
internal/utils/cache/redis.go
internal/utils/cache/redis_auto_type_test.go
internal/utils/cache/redis_test.go

closes #20 
E2E-tested on my environment.

support REDIS_USE_SSL config parameter

---

dify.rb
docs/build_homebrew.md

Update the installation command
```bash
brew install --formula ./dify.rb
```

bump: cli version

---

internal/core/plugin_manager/local_runtime/stdio_handle.go

fix
fatal error: concurrent map iteration and map write

fix fatal error: concurrent map iteration and map write

---

internal/core/plugin_manager/local_runtime/environment_python.go
internal/types/models/curd/atomic.go

This commit introduces two main changes:
1. Pre-compilation of Python plugins during environment initialization to improve initial runtime performance
2. Updated plugin upgrade logic to use PluginID instead of string identifier for agent strategy installation

feat: add Python plugin pre-compilation and update plugin upgrade logic

---

internal/cluster/plugin_test.go
internal/core/plugin_daemon/backwards_invocation/transaction/full_duplex_event_writer.go
internal/core/plugin_daemon/generic.go
internal/core/plugin_manager/debugging_runtime/io.go
internal/core/plugin_manager/local_runtime/io.go
internal/core/plugin_manager/serverless_runtime/io.go
internal/core/plugin_manager/watcher_test.go
internal/core/session_manager/session.go
pkg/entities/plugin_entities/runtime.go

Modify session write method to include a new plugin access action parameter across multiple runtime implementations. This change allows for more granular tracking and handling of plugin interactions by introducing an optional action context to the write method.

feat: add plugin access action to session write method

---

internal/core/plugin_manager/local_runtime/stdio_handle.go

Modify stdout listener handling to avoid potential deadlocks by:
- Copying listeners before invocation
- Executing listener callbacks outside of the lock
- Separating listener retrieval and execution steps

fix: prevent potential deadlock in stdio handler listener invocation

---

internal/utils/http_requests/http_warpper.go

The same code is right above the modification.

fix: remove duplicate code

---

docker/local.dockerfile
internal/core/plugin_manager/local_runtime/environment_python.go

1. Introduce uv to speedup dependencies installing
2. precompile and preload dify_plugin(especially gevent.monkey) to reduce times of first launching

enhance: introduce uv

---

docker/local.dockerfile

Preload tiktoken while build the image to make sure no more hot loading 
Closes: [14565](https://github.com/langgenius/dify/issues/14565)

enhance: preload tiktoken

---

internal/oss/tencent_cos/tencent_cos_storage.go

`List` method has a bug , not querying all plugins , fix it

fix bug: oss tencent cos list dir

---

.env.example

Description
-----------------
Specifies the SSL mode for the database connection explicitly in the .env. 
Default value is disable.

Specifies the SSL mode for the database connection

---

.env.example
docker/local.dockerfile
internal/core/plugin_manager/launcher.go
internal/core/plugin_manager/local_runtime/environment_python.go
internal/core/plugin_manager/local_runtime/type.go
internal/core/plugin_manager/manager.go
internal/types/app/config.go

For the local development environment, `uv` is typically installed using `pipx`, so it cannot be located by `find_uv_bin`.

add uv path config

---

cmd/commandline/bundle/init.go
cmd/commandline/plugin/init.go
cmd/commandline/plugin/template.go
cmd/commandline/plugin/templates/.github/workflows/plugin-publish.yml
cmd/commandline/plugin/templates/python/.difyignore
cmd/commandline/plugin/templates/python/GUIDE.md

Added GitHub CI workflow to the template files created by the CLI.

feat(cli): add github ci to template

---

internal/core/plugin_daemon/tool_service.go
internal/core/plugin_manager/debugging_runtime/hooks.go
internal/utils/stream/stream.go
internal/utils/stream/stream_test.go

- Removed unnecessary complexity from the InvokeTool function by eliminating the blob handling logic and directly returning the response.
- Updated the stream implementation to support blocking writes, allowing for better management of data flow when the buffer is full.
- Added tests for the new blocking write functionality to ensure reliability and performance under high load conditions.

refactor(plugin_daemon): simplify InvokeTool function and enhance stream handling

---

internal/core/plugin_manager/local_runtime/environment_python.go

fix: remove duplicated code

---

.github/workflows/benchmark.yml
README.md
internal/utils/stream/stream_benchmark_test.go

- Introduced a GitHub Actions workflow for benchmarking Go code, triggered on pushes to the main branch and pull requests.
- Added a benchmark test for the stream package to measure performance of the Write method under concurrent conditions.

feat: add benchmark workflow

---

.github/workflows/build-push.yml
.github/workflows/publish-cli.yaml
.github/workflows/tests.yml

- update Github Actions versions to latest
- no breaking changes in usages

chore: modernize GHA versions

---

.github/workflows/build-push.yml

- Modified the conditional for the build job to skip execution on pull requests when the `skip_on_pr` flag is set to true for specific services.

chore: update build-push workflow to skip builds on pull requests (#233)

---

internal/core/plugin_daemon/access_types/access.go
internal/core/plugin_daemon/oauth_service.go
internal/server/controllers/oauth.go
internal/server/http_server.go
internal/service/invoke_oauth.go
pkg/entities/oauth_entities/oauth.go
pkg/entities/plugin_entities/datasource_declaration.go
pkg/entities/plugin_entities/oauth.go
pkg/entities/plugin_entities/tool_declaration.go
pkg/entities/requests/oauth.go

- Added OAuth service methods for getting authorization URLs and credentials.
- Updated access types to include OAuth-related actions.
- Created new controller for handling OAuth requests.
- Introduced entities for OAuth results and requests.
- Enhanced plugin entities to support OAuth schema in tool declarations.

feat: implement OAuth functionality

---

cmd/commandline/plugin.go
cmd/commandline/plugin/category.go
cmd/commandline/plugin/init.go
cmd/commandline/plugin/init_test.go
cmd/commandline/plugin/language.go
cmd/commandline/plugin/profile.go
cmd/commandline/plugin/version_require.go
cmd/commandline/test.go

- Added new flags for plugin initialization, allowing users to specify author, name, description, and various permissions.
- Implemented InitPluginWithFlags function to handle the new parameters and validate input.
- Introduced methods to set category, language, and minimal Dify version within the plugin model.
- Enhanced profile management by adding methods to set author and name directly.
- Improved category and language selection with dedicated setter methods.

feat: enhance plugin initialization with configurable parameters

---

.env.example
internal/core/dify_invocation/real/encrypt_test.go
internal/core/dify_invocation/real/http_client.go
internal/core/dify_invocation/real/http_request.go
internal/core/dify_invocation/real/types.go
internal/core/plugin_manager/manager.go
internal/types/app/config.go
internal/types/app/default.go

fix: #258 
fix: https://github.com/langgenius/dify/issues/18729

feat: add read & write timeout config

---

internal/core/plugin_manager/media_transport/installed_bucket.go

- Implemented validation in NewInstalledBucket to log warnings for non-alphanumeric starting characters and empty paths for installedPath.
- Updated parameter naming for consistency across methods in InstalledBucket, enhancing code clarity.

feat: add input validation for installed bucket path

---

.script/build_plugin_cli.sh
.script/build_plugin_daemon.sh

- add scripts `build_plugin_cli.sh` and `build_plugin_daemon.sh` for building binary locally for different OS systems and the chip rchitecturse

build: add scripts for local binary builds

---

cmd/commandline/plugin/templates/python/requirements.txt

- bump dify_plugin in plugin dependency template to 0.2.x

dep: bump dify_plugin in plugin dependency template to 0.2.x

---

internal/oss/aliyun/aliyun_oss_storage.go

1. Fix the issue where the List method of Alibaba Cloud OSS did not correctly return plugin file paths.
2. Add exception handling for parse failures.

fix: Fix the issue where the List method of Alibaba Cloud OSS did not correctly return plugin file paths.

---

internal/types/models/curd/atomic.go

- Renamed parameters for consistency and clarity, changing `tenant_id`, `plugin_unique_identifier`, and `install_type` to `tenantId`, `pluginUniqueIdentifier`, and `installType` respectively across multiple functions.
- Updated corresponding database queries to reflect the new parameter names, enhancing code readability and maintainability.

chore: coding style

---

pkg/entities/requests/tool.go

Added MCP tool type to enable Agent strategy plugins to invoke MCP tool types.

feat: add mcp tool type

---

cmd/commandline/plugin/templates/python/.difyignore

Prevent packaging repetitively.
fixes: https://github.com/langgenius/dify-plugins/issues/612
fixes: https://github.com/langgenius/dify-plugins/issues/234

fix: prevent duplicate packaging

---

internal/core/plugin_manager/media_transport/installed_bucket.go

skip error plugin names

---

cmd/commandline/plugin/templates/python/tool_provider.py
internal/core/plugin_daemon/access_types/access.go
internal/core/plugin_daemon/oauth.gen.go
internal/server/controllers/definitions/definitions.go
internal/server/controllers/oauth.gen.go
internal/server/http_server.gen.go
internal/service/oauth.gen.go
pkg/entities/oauth_entities/oauth.go
pkg/entities/requests/oauth.go

- Added RefreshCredentials endpoint to handle OAuth credential refresh requests.
- Introduced RequestOAuthRefreshCredentials structure for request validation.
- Updated access types and actions to include refresh credentials.
- Enhanced server routing and controller logic to support the new functionality.
- Updated OAuth entities to include expiration handling for refreshed credentials.

feat(oauth): implement refresh credentials functionality

---

internal/core/dify_invocation/types.go
pkg/entities/requests/model.go

Fix https://github.com/langgenius/dify-plugin-daemon/issues/418

fix credential type

---

.script/build_plugin_cli.sh

* I have not tested these on Linux or MacOS, I only have windows

Fix OS and architecture detection for Windows
