- docker/local/Dockerfile
In a Docker-based self-hosted environment (Of course I know it's not supported yet :D ), the Python version in the plugin daemon's container is 3.10.
Since version [`0.0.1b45` of the Python SDK](https://pypi.org/project/dify_plugin/0.0.1b45/), the requirement for Python has been changed to version **3.11** or later.
As a result, if version `0.0.1b45` or later is specified in the new plugin's `requirements.txt` (e.g. [Google plugin](https://github.com/langgenius/dify-official-plugins/blob/main/tools/google/requirements.txt)), the daemon will not be able to install that plugin.
```bash
2025-01-04 22:48:48 2025/01/04 13:48:48 launcher.go:181: [INFO]init environment for plugin langgenius/google:0.0.6
2025-01-04 22:48:51 2025/01/04 13:48:51 launcher.go:181: [ERROR]init environment failed: …
```
> feat: bump python version for container image for local platform to 3.12

- .env.example
- internal/core/plugin_manager/launcher.go
- internal/core/plugin_manager/local_runtime/environment_python.go
- internal/core/plugin_manager/local_runtime/type.go
- internal/core/plugin_manager/manager.go
- internal/types/app/config.go
- internal/types/app/default.go
when I install some plugin like `gemini`, `ollama`,  it always raise `init process exited due to long time no activity`.
and after I change the time, all packages installed success.
the time is always larger than 60s,  `gemini`:
`siliconflow`:
> change default process kill time

- cmd/commandline/bundle/profile.go
- cmd/commandline/plugin/profile.go
- pkg/entities/plugin_entities/plugin_declaration.go
The hint state:
```
Bundle name must be 1-128 characters long, and can only contain letters, numbers, dashes and underscores
```
However, uppercase letters are currently not allowed.
> change hint of input uppercase letter in plugin name

- cmd/commandline/plugin/templates/python/GUIDE.md
The Python SDK has changed the minimum Python version to 3.11 since version [0.0.1b45](https://pypi.org/project/dify_plugin/0.0.1b45/).
If we on the Python 3.10, we can only install versions prior to 0.0.1b44 with pip.
This PR updates the documentation accordingly.
> docs: bump minimal python version to 3.11 to follow changes on dify-plugin-sdks

- internal/oss/s3/s3_storage.go
- internal/types/app/config.go
Currently only static IAM credentials are supported to access S3 buckets. It would be great if we could use IAM role credentials when running Dify on AWS, just [like Dify itself](https://github.com/langgenius/dify/blob/56e15d09a9e94de963dd5fc38c7455a7aaee99f3/api/extensions/storage/aws_s3_storage.py#L18-L36). This PR enables it.
I found adding unit test for this difficult but let me know if you think it is required 🙏  At least I E2E-tested on my AWS environment.
> support AWS credentials from IAM role

- cmd/commandline/plugin/templates/python/llm.py
`LargeLanguageModel` is used but has not been imported.
```py
class {{ .PluginName | SnakeToCamel }}LargeLanguageModel(LargeLanguageModel):
```
> fix: add missing import for llm template

- internal/core/plugin_manager/local_runtime/run.go
closes #29 
If it is the expected behavior to pass environment variables to local runtime process (not sure about this, but at least it is desired for self-host environment), this should be the fix.
> fix environment variables are not propagated to local runtime

- pkg/entities/model_entities/llm.go
To resolve the Tool invoke error.
**before**
**after**
> fix: make description field optional in PromptMessageTool

- pkg/entities/plugin_entities/config.go
- pkg/entities/plugin_entities/tool_declaration_test.go
The correct definition in `dify` and `dify-plugin-sdk` is `help`, not `helper`. 
After the fix, the help message will display correctly.
> fix tool provider panel not display help message

- pkg/entities/model_entities/llm.go
MultiModal content supports both base64 and url format, but lost in dify-plugin-daemon server
> Add missing `url` field of PromptMessageContent

- internal/core/plugin_manager/local_runtime/stdio_handle.go
Move last active time update to occur on each data receipt to ensure more accurate tracking of plugin activity
> fix: optimize plugin last active time tracking in stdio handler

- internal/db/init.go
- internal/db/pg_test.go
- internal/types/app/config.go
- internal/types/app/default.go
- Add support for connecting to a default database when target database connection fails
- Introduce new configuration parameter `DBDefaultDatabase` with default value "postgres"
- Modify `initDifyPluginDB` to attempt connection to default database and create target database if needed
- Update test case to include default database parameter
> feat: enhance database initialization with fallback connection strategy

- internal/core/plugin_manager/debugging_runtime/connection_key.go
This pull request addresses the issue of the "CROSSSLOT Keys in request don't hash to the same slot" error, which occurs when Redis commands involve keys that are not hashed to the same slot in a clustered environment.
Changes Made:
1. Updated Redis command logic to ensure that all keys involved in transactions or multi-key operations are hashed to the same slot.
2. Modified the data distribution strategy to align with Redis cluster requirements, ensuring key patterns are consistent with slot allocation.
> fix: Fix CROSSSLOT Error in Redis Commands

- internal/core/plugin_manager/launcher.go
- internal/core/plugin_manager/local_runtime/environment_python.go
- internal/core/plugin_manager/local_runtime/type.go
- internal/core/plugin_manager/manager.go
- internal/core/plugin_manager/serverless.go
- internal/core/plugin_manager/watcher_test.go
- internal/types/app/config.go
- internal/types/app/default.go
Enhance Python plugin environment initialization with new configuration options:
- Add support for pip prefer binary flag
- Add pip verbose mode
- Add extra pip arguments configuration
- Set default values for new pip-related configuration options
> feat: add pip configuration options for plugin environment setup

- internal/core/plugin_daemon/model_service.go
fix https://github.com/langgenius/dify/issues/15025
I add this code to plugin sdk [here](https://github.com/langgenius/dify-plugin-sdks/blob/b936b1be9f91d1ae6725604ad8938b80cf42c635/python/dify_plugin/core/plugin_executor.py#L217) for debug:
```
for i, chunk in enumerate(b):
with open(f'tts_debug_chunk_{i}.bin', 'wb') as f:
f.write(chunk)
yield {"result": binascii.hexlify(chunk).decode()}
```
also add this code to api server [here](https://github.com/langgenius/dify/blob/4aaf07d62af180439a4871a2191e45b610929881/api/core/plugin/manager/model.py#L403) for debug:
```
for i, result in enumerate(response):
hex_str = result.result
decoded = binascii.unhexlify(hex_str)
with open(f'received_chunk_{i}.bin', 'wb') as f:
f.write(decoded)
yield decoded
```
always get  `tts_debug_chunk_70.bin` files …
> fix tts not work well

- internal/core/plugin_manager/media_transport/installed_bucket.go
- internal/oss/local/local_storage.go
closes #35 
closes https://github.com/langgenius/dify/issues/14769
closes https://github.com/langgenius/dify/issues/14534
I moved the exists operation from installedBucket.List to localStorage.List. This makes the exist function for S3 storage no longer called, fixing the issue without changing any existing behavior for localStorage.
Since some implementation of storage does not require to check the existence of a directory before list operation, I believe it makes more sense to run an exists function inside a list function of each implementation, instead of handling it from caller.
> fix: plugins are not installed when plugin-daemon is restarted and plugins are stored on s3

- internal/utils/cache/redis.go
After connections to redis has disconnected, daemon will fall into a deadloop and cause a high CPU usage
> fix: improve Redis subscription error handling with logging and retry

- internal/server/endpoint.go
- internal/server/endpoint_test.go
- internal/server/http_server.go
- internal/service/endpoint.go
Modify endpoint-related functions to support configurable maximum execution time:
- Update EndpointHandler signature to include maxExecutionTime
- Pass max execution timeout from config to endpoint service
- Modify timeout mechanism to use configurable duration instead of hardcoded 240 seconds
> feat: Add max execution time parameter to endpoint handling

- internal/core/plugin_manager/local_runtime/environment_python.go
Remove duplicate proxy configuration logic when installing Python packages, keeping only the mirror URL configuration
> fix: Remove redundant proxy handling in Python environment setup

- pkg/entities/model_entities/llm.go
This PR changes the `PromptMessageContent` structure to allow having the `Detail` (`detail` in JSON) key.
By this change, the "Resolution" configuration for the vision requests that are sent from the API side will be handled and passed to LLM model correctly.
Closes #109
> fix: respect resolution settings for vision sent from api

- internal/core/plugin_manager/local_runtime/environment_python.go
This PR changes `uv` command to use proxy if it is specified by `HTTP_PROXY` and/or `HTTPS_PROXY`.
This is follow-up for #99 for #102, also closes #118
> fix: pass HTTP_PROXY and HTTPS_PROXY to uv process

- internal/core/plugin_manager/launcher.go
- internal/core/plugin_manager/local_runtime/environment_python.go
- internal/core/plugin_manager/local_runtime/type.go
- internal/core/plugin_manager/manager.go
- internal/types/app/config.go
Introduce `pythonCompileAllExtraArgs` to allow users to pass extra arguments to the Python `compileall` command. This enhancement enables more flexible compilation options for plugins by extending the configuration in the plugin manager and local runtime components.
- Updated `launcher.go` to include `PythonCompileAllExtraArgs` in the runtime configuration.
- Modified `environment_python.go` to handle the additional compile arguments.
- Added new configuration fields in `type.go` and `config.go`.
- Adjusted initialization in `manager.go` to accept the new configuration parameter.
> feat(plugin-manager): add support for additional Python compileall arguments

- internal/core/plugin_manager/local_runtime/environment_python.go
Updated the error handling in the InitPythonEnvironment function to log pre-compilation errors instead of returning them. This change addresses issues with plugins referencing broken SDKs while still functioning correctly. Additionally, corrected the log message for pre-loading plugins to reflect the accurate state.
Fixes: https://github.com/langgenius/dify/issues/16292
> fix(plugin-manager): log pre-compilation python errors instead of raises it outside to avoid plugins to broken

- internal/utils/cache/redis.go
- internal/utils/cache/redis_auto_type.go
- internal/utils/cache/redis_auto_type_test.go
add a new function named `store` for internal use, without calling serialKey.
modify `TestAutoTypeWithGetter` to call twice, check if cache hit.
> BUGFIX: fix AutoGetWithGetter will never hit cache issue.

- internal/utils/cache/redis.go
- internal/utils/cache/redis_auto_type.go
- internal/utils/cache/redis_test.go
Add get/delete implement, without `serialKey`, for internal use, as metioned in #128
> Add get/delete implement, for internal use.

- .gitignore
- internal/core/plugin_manager/local_runtime/environment_python.go
The plugin is developed for Python 3.12. However, when the system Python version differs (e.g., 3.13), the plugin may fail to run correctly.
To ensure compatibility, we'll configure uv to default to Python 3.12, matching the manifest specification.
> fix: some time uv venv wrong python version

- internal/utils/mapping/sync.go
- internal/utils/mapping/sync_test.go
**Thread-Safety Issue:**
> Even if atomic operations (e.g., atomic.AddInt32) and mutexes (e.g., sync.RWMutex) are used, modifying multiple variables (e.g., store and len) in a single method creates a critical section. For example:
> In Store, the sequence Load → AddInt32 → Store is not atomic as a whole, leading to potential race conditions.
> If two goroutines simultaneously call Store for the same key, both might see loaded = false and increment len, resulting in an incorrect count.
> 
**len Inaccuracy:**
> The len field is intended to track the number of unique keys in the map.
> In the original Store method, len was incremented unconditionally, even when overwriting an existing key. This caused len to overcount entries.
```
// Goroutine 1
m.Store("key", 1)  // loaded = false → len++ → …
```
> fix: thread safety issue and len inaccuracy in Map

- internal/utils/cache/redis_test.go
fix cache unit test.
```
Error: internal/utils/cache/redis_test.go:286:62: not enough arguments in call to InitRedisClient
have (string, string, bool)
want (string, string, bool, int)
```
> fix unit test

- internal/core/dify_invocation/tester/mock.go
- pkg/entities/model_entities/llm.go
Solves high CPU usage of dify-api container caused by LLMResultChunk decoding
Related: 
- https://github.com/langgenius/dify/issues/17799
- https://github.com/langgenius/dify-official-plugins/issues/648
> enhancement(llm): remove non-required PromptMessages field from LLMResultChunk

- internal/core/dify_invocation/types.go
- internal/core/persistence/persistence.go
- internal/core/persistence/type.go
- internal/core/persistence/wrapper.go
- internal/core/plugin_daemon/backwards_invocation/task.go
Currently,  get or delete a non-existent key will raises an exception, although this is a common operation. 
On the other hand, we can use the storage as a pipeline, frequently retrieving data from it. This results in numerous error logs on the daemon. Using 'exists' can significantly reduce these error logs.
> add `exist` for self.session.storage

- internal/core/plugin_manager/launcher.go
- internal/core/plugin_manager/local_runtime/environment_python.go
- internal/core/plugin_manager/local_runtime/run.go
- internal/core/plugin_manager/local_runtime/type.go
- internal/core/plugin_manager/manager.go
- internal/types/app/config.go
This PR adds support for `NO_PROXY` environment variable for initialization process.
Closes #168
Pass the following environment variables and try to install any plugin.
```yaml
environment:
HTTP_PROXY: http://proxy.example.com:8080/
HTTPS_PROXY: http://proxy.example.com:8080/
NO_PROXY: pypi.org,pythonhosted.org
```
Note that `http://proxy.example.com:8080/` is a non-existing proxy, so all traffic which is routed through the proxy, it will always fail.
However, if `NO_PROXY` works, the installation should succeed.
Even though `pypi.org` is in `NO_PROXY`, it is routed through a proxy, which causes installation to fail.
```bash
2025-04-12 23:42:40 2025/04/12 14:42:40 runtime_lifetime.go:80: [INFO]init environment for plugin langgenius/openai:0.0.16
2025-04-12 23:42:45 2025/04/12 14:42:45 …
```
> feat: support NO_PROXY for initialization process

- internal/core/persistence/persistence.go
- internal/core/persistence/persistence_test.go
- internal/core/persistence/wrapper.go
fix(persistence): correct path traversal checks in tests and implementation
- Updated test cases to expect no errors for valid paths with double slashes and mixed traversal.
- Enhanced the `checkPathTraversal` method to clean the key using `path.Clean` to prevent path traversal vulnerabilities.
- Removed redundant checks in the `getFilePath`, `Save`, `Load`, and `Delete` methods, simplifying the code while maintaining security.
> fix(persistence): correct path traversal checks in tests and implementation

- README.md
- fix source for downloading the binary file from dify's main repo to dify-plugin-daemon's repo as https://github.com/langgenius/dify-plugin-daemon/releases
- Update cli tool installation guidance in README.md
> doc: update cli tool installation guidance in README.md

- .github/workflows/benchmark.yml
- .github/workflows/publish-cli.yaml
- .github/workflows/tests.yml
- As Go 1.23 is required in go.mod since #158, all the Go version in Github actions should be updated to 1.23 as well for testing and publishing.
> chore: align go version in GHA to 1.23

- pkg/entities/model_entities/llm.go
- pkg/entities/model_entities/llm_test.go
- Implemented a compatibility layer in LLMResultChunk to ensure backward compatibility with the old format by adding a `PromptMessages` field.
- Added a new test case `TestLLMResultChunkCompatibility` to verify the JSON marshaling behavior of the updated LLMResultChunk structure.
> feat: add backward compatibility for LLMResultChunk and new test case

- internal/cluster/clutser_test.go
- internal/core/persistence/persistence_test.go
- internal/core/plugin_manager/debugging_runtime/connection_key_test.go
- internal/core/plugin_manager/debugging_runtime/server_test.go
- internal/core/plugin_manager/manager.go
- internal/types/app/config.go
- internal/utils/cache/redis.go
- internal/utils/cache/redis_auto_type_test.go
- internal/utils/cache/redis_test.go
issue #144 related
This pull request introduces support for authenticating Redis connections using both a username and a password. This enhances compatibility with Redis hosting providers like AWS ElastiCache that require username-based authentication in addition to a password.
Motivation:
Modern Redis deployments, particularly managed services like ElastiCache (with RBAC enabled), often mandate the use of a username for authentication alongside the password. The previous implementation only supported password authentication, preventing connections to these types of Redis instances.
Changes:
Configuration: Added a new optional configuration field RedisUser to internal/types/app/config.go, loaded from the REDIS_USERNAME environment variable.
Redis Client: Modified getRedisOptions and …
>  Add optional Redis username authentication

- cmd/commandline/plugin/templates/python/moderation.py
- Modified the docstring in the moderation model to use the correct format for the plugin name, enhancing clarity and consistency in the documentation.
> fix: update moderation model docstring to reflect plugin name correctly

- cmd/commandline/plugin.go
- cmd/commandline/plugin/init.go
- cmd/commandline/plugin/init_test.go
- cmd/commandline/plugin/profile.go
- pkg/entities/plugin_entities/plugin_declaration.go
Related PR:
- https://github.com/langgenius/dify-plugin-sdks/pull/134
- https://github.com/langgenius/dify/pull/19337
feat: add repository URL support for plugin manifest
- Introduced a new optional flag for specifying the plugin repository URL during initialization.
- Updated the InitPluginWithFlags function to handle the new repository parameter.
- Enhanced profile management to include repository input.
- Modified related tests to validate the new repository functionality.
> feat: add repository URL support for plugin manifest

- internal/core/plugin_manager/local_runtime/stdio.go
Fixes #254
- Adjusted the buffer size settings in the stdioHolder to utilize configurable values for stdout buffer size and maximum buffer size, enhancing flexibility in plugin output handling.
> fix: update stdio buffer size configuration in stdioHolder

- docker/local.dockerfile
- docker/serverless.dockerfile
- dockerfile improvements
- correct `FROM ... as` to `FROM ... AS` for setting base image, eliminating the warning message in docker image build `WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)`
- move the copying action of `main` to latter steps , to reuse the previous built layer as many as possible especially for repeated builds and also help to extraction layer compressions earlier for image pulling
- squeeze the file copying into single command to reduce image layers
> chore: dockerfile improvements

- cmd/commandline/plugin/templates/.env.example
- cmd/commandline/plugin/templates/python/GUIDE.md
- use `REMOTE_INSTALL_URL` config in `dify_plugin` SDK introduced by (https://github.com/langgenius/dify-plugin-sdks/pull/136 ) to set debugging host and port
> feat: support REMOTE_INSTALL_URL in plugin cli template

- internal/core/plugin_manager/install_to_serverless.go
- internal/core/plugin_manager/serverless.go
- internal/core/plugin_manager/serverless_connector/launch.go
- internal/server/constants/constants.go
- internal/server/controllers/plugins.go
- internal/server/http_server.go
- internal/server/middleware.go
- internal/service/install_plugin.go
- internal/types/app/config.go
- Implemented ReinstallToAWSFromPkg method to allow reinstallation of plugins on AWS Lambda, updating function URL and name.
- Added clearServerlessRuntimeCache method to manage serverless runtime cache.
- Enhanced LaunchPlugin to support an ignoreIdempotent flag for forced reinstallation.
- Introduced admin API endpoints for plugin reinstallation, secured with an API key validation middleware.
- Updated configuration to include AdminApiEnabled and AdminApiKey settings.
> feat: add plugin reinstallation functionality and admin API support

- .env.example
- internal/core/plugin_manager/manager.go
- internal/types/app/config.go
- internal/utils/cache/redis.go
Added support for Redis Sentinel mode to the Redis client, enabling automatic discovery and connection to the primary node through Sentinel. Updated relevant configuration files and initialization logic to support Sentinel mode configuration and connection.
refs: https://github.com/langgenius/dify-plugin-daemon/issues/274
> feat(redis): Add support for Redis Sentinel mode

- internal/utils/cache/redis.go
- internal/utils/cache/redis_test.go
- Introduced a new test case `TestLock` to validate the behavior of the Redis locking mechanism under concurrent access.
- Enhanced the `Lock` function to improve error handling and ensure proper locking behavior.
- Utilized `sync.WaitGroup` and atomic operations to measure wait times during lock acquisition, ensuring the lock behaves as expected under high concurrency.
> fix(lock): Add concurrency test for Redis lock functionality

- cmd/commandline/signature/signature_test.go
- internal/service/plugin_decoder.go
- pkg/plugin_packager/consts/verification.go
- pkg/plugin_packager/decoder/decoder.go
- pkg/plugin_packager/decoder/entities.go
- pkg/plugin_packager/decoder/fs.go
- pkg/plugin_packager/decoder/verifier.go
- pkg/plugin_packager/decoder/zip.go
- pkg/plugin_packager/signer/withkey/sign_with_key.go
- Updated the  method in the  interface to remove the  parameter, simplifying its usage.
- Introduced a new  function to provide a default verification structure.
- Added a  file to store verification data, improving the plugin signing process.
- Enhanced tests in  to validate the verification process, ensuring proper handling of success and failure scenarios.
- Refactored related code to accommodate the new verification structure and improve overall maintainability.
> fix(signature): signature dose not work as expected, if upload new pkg to old dify

- cmd/commandline/plugin/package.go
- pkg/plugin_packager/packager/packager.go
> add packaged file info when plugin package larger than max size

- internal/core/plugin_manager/local_runtime/stdio.go
Directly fetch and invoke the listener for a given session_id instead of iterating over the entire listener map.
> refactor(local_runtime): optimize listener lookup in stdioHolder

- internal/types/app/config.go
when using redis sentinel, REDIS_HOST and REDIS_PORT are useless, but leading to the error
```
main.go:25: [PANIC]Invalid configuration: Key: 'Config.RedisHost' Error:Field validation for 'RedisHost' failed on the 'required' tag
```
> fix: launch error when using redis sentinel

- internal/core/plugin_daemon/generic.go
**Description:**  
When the `plugin-daemon` receives responses from a tool, if the tool returns data too quickly, the queue of the stream will be full, finally causing data to be discarded without any error log.  
**Steps to Reproduce:**  
1. Develop an `unzip` plugin.  
2. Package 100 PDF files (each ~500KB) into a single ZIP archive.  
3. Use the `unzip` plugin in a workflow to extract the files.  
4. **Result:** The `unzip` plugin outputs only 20 to 50+ PDFs each time, losing a significant portion of the files.  
**Proposed Fix:**  
Replace the stream object’s `Write` method with `WriteBlocking` to ensure synchronous handling.
> fix:response data will be discard if tool/llm response buffer overflow

- internal/core/dify_invocation/invcation.go
- internal/core/dify_invocation/real/http_request.go
- internal/core/dify_invocation/tester/mock.go
- internal/core/dify_invocation/types.go
- internal/core/plugin_daemon/backwards_invocation/task.go
- pkg/entities/model_entities/llm.go
- Introduced a new method InvokeLLMWithStructuredOutput to the BackwardsInvocation interface for handling structured output requests.
- Added corresponding request and response types to support structured output.
- Implemented the method in both RealBackwardsInvocation and MockedDifyInvocation for testing purposes.
- Updated permission handling and task execution for the new structured output invocation type.
This enhancement allows for more flexible and detailed responses from the LLM, improving the overall functionality of the invocation system.
Please provide any additional context that would …
> feat: add InvokeLLMWithStructuredOutput functionality

- internal/server/controllers/health_check.go
- internal/server/http_server.go
- Implemented middleware to track active requests and active dispatch requests using atomic counters.
- Updated health check response to include counts of active requests and active dispatch requests.
- Integrated the new middleware into the HTTP server and plugin dispatch group for improved monitoring.
> feat: add active request tracking to health check and dispatch routes

- internal/core/plugin_manager/lifecycle/full_duplex.go
This PR fixes a debugging experience issue where remote plugin reconnection fails after quick restart cycles. The problem was caused by a mandatory 5-second sleep delay in the plugin lifecycle that prevents rapid plugin restarts during development.
**Changes made:**
- Modified `internal/core/plugin_manager/lifecycle/full_duplex.go` to skip the 5-second sleep delay for remote runtime plugins
- Added runtime type check to only apply the delay for non-remote plugins
- Improves developer experience during remote plugin debugging without affecting production behavior
This change allows developers to quickly restart remote plugins during debugging without encountering "no available node, plugin not found" errors.
Fixes #386
**Problem Context:**
When debugging remote plugins, developers …
> Remote plugin debugging: Skip 5-second sleep delay for faster development iteration

- internal/core/plugin_manager/watcher.go
Fixes #416 
Fix the frequent pull issue of the plugin by prioritizing the check to see if the plugin is already running. If it is, do not pull the remote file to start it again.
> fix Frequent plugin pulls

- internal/server/endpoint.go
- internal/server/middleware.go
- internal/service/endpoint.go
- internal/service/install_plugin.go
- internal/service/install_service/state.go
- internal/service/setup_endpoint.go
- internal/types/models/curd/atomic.go
- internal/utils/cache/helper/keys.go
This PR implements Redis caching for the `FetchPluginInstallation` middleware to improve performance by reducing database queries for frequently accessed plugin installation data.
**Problem**: The `FetchPluginInstallation` middleware was called frequently and performed a database query on each request, causing performance issues due to repeated database access for the same plugin installation data.
**Solution**: Added Redis caching using the existing `AutoGetWithGetter` pattern to reduce database load and improve response times for frequent plugin installation lookups.
Closes #399 
- [] I have added unit tests where necessary and they pass successfully
**Files Modified:**
1. **`internal/utils/cache/helper/keys.go`** (new file)
- Added `PluginInstallationCacheKey()` function for consistent …
> Add Redis caching to FetchPluginInstallation middleware for performance optimization

- internal/core/plugin_daemon/backwards_invocation/request.go
- internal/core/plugin_daemon/backwards_invocation/transaction/aws_event_handler.go
- internal/core/plugin_daemon/backwards_invocation/transaction/aws_event_writer.go
- internal/core/plugin_daemon/generic.go
- internal/core/plugin_manager/install_to_serverless.go
- internal/core/plugin_manager/serverless_connector/launch.go
- internal/core/plugin_manager/serverless_runtime/io.go
- internal/server/app.go
- internal/server/http_server.go
- internal/service/aws_transaction.go
- internal/service/install_plugin.go
- Updated AWS-related types and functions to reflect Serverless terminology, including renaming `AWSTransactionHandler` to `ServerlessTransactionHandler` and `AWSTransactionWriter` to `ServerlessTransactionWriter`.
- Adjusted error messages and comments to align with the new naming conventions.
- Modified installation functions to use Serverless terminology for clarity and consistency across the codebase.
> refactor: rename AWS references to Serverless in plugin daemon

- internal/core/plugin_manager/install_to_serverless.go
- internal/core/plugin_manager/serverless_connector/connector.go
- internal/core/plugin_manager/serverless_connector/launch.go
- internal/service/install_plugin.go
When installing plugin to serverless, propagate plugin unique identifier to serverless control plane for easier resource aggregation.
> feat: propagate plugin unique identifier to serverless control plane
